import { ChatRoom, User } from './chat.types';

// Mock users
export const mockUsers: Record<string, User> = {
  'u1': {
    id: 'u1',
    name: 'Sarah Chen',
    avatar: 'https://randomuser.me/api/portraits/women/32.jpg',
    isOnline: true,
    lastSeen: '2 minutes ago',
  },
  'u2': {
    id: 'u2',
    name: 'Mike Johnson',
    avatar: 'https://randomuser.me/api/portraits/men/44.jpg',
    isOnline: true,
    lastSeen: 'Just now',
  },
  'u3': {
    id: 'u3',
    name: 'Emma Rodriguez',
    avatar: 'https://randomuser.me/api/portraits/women/63.jpg',
    isOnline: false,
    lastSeen: '1 hour ago',
  },
  'u4': {
    id: 'u4',
    name: 'David Kim',
    avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
    isOnline: true,
    lastSeen: '5 minutes ago',
  },
  'u5': {
    id: 'u5',
    name: 'Alex Thompson',
    avatar: 'https://randomuser.me/api/portraits/men/67.jpg',
    isOnline: false,
    lastSeen: '1 day ago',
  },
  'u6': {
    id: 'u6',
    name: 'Yuki Tanaka',
    avatar: 'https://randomuser.me/api/portraits/women/91.jpg',
    isOnline: true,
    lastSeen: '10 minutes ago',
  },
  'me': {
    id: 'me',
    name: 'You',
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    isOnline: true,
  },
};

// Enhanced mock chat rooms
export const mockChatRooms: Record<string, ChatRoom> = {
  '1': {
    roomId: '1',
    name: 'Bali Travelers',
    description: 'Share experiences, tips, and connect with fellow travelers exploring the beautiful island of Bali',
    participants: 124,
    location: 'Bali, Indonesia',
    avatar: 'https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=100&h=100&fit=crop',
    category: 'travel',
    tags: ['rice-terraces', 'temples', 'beaches', 'culture', 'food'],
    createdAt: '2024-01-15T10:00:00Z',
    lastMessage: 'Has anyone visited the rice terraces?',
    lastMessageTime: '10:45 AM',
    unreadCount: 3,
    isSubscribed: true,
    moderators: ['u1', 'u2'],
    rules: [
      'Be respectful to all members',
      'No spam or promotional content',
      'Share authentic travel experiences',
      'Help fellow travelers with genuine advice'
    ],
    messages: [
      {
        id: 'm1',
        user: mockUsers['u1'],
        text: 'Has anyone visited the rice terraces? Worth the trip?',
        timestamp: '10:45 AM',
        date: 'Today',
        likes: 5,
        dislikes: 0,
        likedBy: ['u2', 'u3', 'u4', 'u5', 'me'],
        dislikedBy: [],
      },
      {
        id: 'm2',
        user: mockUsers['u2'],
        text: 'Absolutely! Tegalalang rice terraces are stunning. Go early morning to avoid crowds. The light is perfect for photos too.',
        timestamp: '10:48 AM',
        date: 'Today',
        likes: 8,
        dislikes: 0,
        likedBy: ['u1', 'u3', 'u4', 'u5', 'u6', 'me'],
        dislikedBy: [],
      },
      {
        id: 'm3',
        user: mockUsers['u3'],
        text: 'I agree with Mike. Also consider visiting Jatiluwih rice terraces if you want something less touristy. It\'s a bit farther but worth it.',
        timestamp: '10:52 AM',
        date: 'Today',
        likes: 6,
        dislikes: 1,
        likedBy: ['u1', 'u2', 'u4', 'u6', 'me'],
        dislikedBy: ['u5'],
      },
      {
        id: 'm4',
        user: mockUsers['u1'],
        text: 'Thanks for the tips! Any food recommendations nearby?',
        timestamp: '10:55 AM',
        date: 'Today',
        likes: 3,
        dislikes: 0,
        likedBy: ['u2', 'u4', 'me'],
        dislikedBy: [],
      },
      {
        id: 'm5',
        user: mockUsers['u4'],
        text: 'There\'s a small warung (local restaurant) at the entrance of Tegalalang that serves amazing Nasi Campur. Can\'t remember the name but you can\'t miss it!',
        timestamp: '11:02 AM',
        date: 'Today',
        likes: 7,
        dislikes: 0,
        likedBy: ['u1', 'u2', 'u3', 'u5', 'u6', 'me'],
        dislikedBy: [],
      },
      {
        id: 'm6',
        user: mockUsers['u2'],
        text: 'Also, don\'t forget to bring cash for the entrance fee and small donations at different viewpoints.',
        timestamp: '11:10 AM',
        date: 'Today',
        likes: 4,
        dislikes: 0,
        likedBy: ['u1', 'u3', 'u4', 'me'],
        dislikedBy: [],
      },
    ],
  },
  '2': {
    roomId: '2',
    name: 'Tokyo Adventures',
    description: 'Discover the vibrant culture, amazing food, and hidden gems of Tokyo',
    participants: 98,
    location: 'Tokyo, Japan',
    avatar: 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=100&h=100&fit=crop',
    category: 'culture',
    tags: ['cherry-blossoms', 'temples', 'food', 'nightlife', 'shopping'],
    createdAt: '2024-01-10T15:30:00Z',
    lastMessage: 'The cherry blossoms are beautiful this time of year!',
    lastMessageTime: 'Yesterday',
    unreadCount: 1,
    isSubscribed: false,
    moderators: ['u5'],
    rules: [
      'Share respectful cultural insights',
      'No inappropriate content about local customs',
      'Help newcomers navigate the city'
    ],
    messages: [
      {
        id: 'm1',
        user: mockUsers['u5'],
        text: 'The cherry blossoms are beautiful this time of year!',
        timestamp: '3:22 PM',
        date: 'Yesterday',
        likes: 12,
        dislikes: 0,
        likedBy: ['u6', 'u1', 'u2', 'u3', 'u4', 'me'],
        dislikedBy: [],
      },
      {
        id: 'm2',
        user: mockUsers['u6'],
        text: 'Yes! Ueno Park and Shinjuku Gyoen are my favorite spots for hanami (cherry blossom viewing).',
        timestamp: '3:30 PM',
        date: 'Yesterday',
        likes: 8,
        dislikes: 0,
        likedBy: ['u5', 'u1', 'u2', 'u4', 'me'],
        dislikedBy: [],
      },
    ],
  },
  '3': {
    roomId: '3',
    name: 'Paris Explorers',
    description: 'Explore the city of lights with fellow travelers and locals',
    participants: 156,
    location: 'Paris, France',
    avatar: 'https://images.unsplash.com/photo-1499996860823-5214fcc65f8f?w=100&h=100&fit=crop',
    category: 'culture',
    tags: ['museums', 'cafes', 'architecture', 'art', 'romance'],
    createdAt: '2024-01-08T12:00:00Z',
    lastMessage: 'I found this amazing little café near the Eiffel Tower',
    lastMessageTime: '2 days ago',
    unreadCount: 0,
    isSubscribed: true,
    moderators: ['u3'],
    messages: [],
  },
  '4': {
    roomId: '4',
    name: 'NYC Foodies',
    description: 'The ultimate guide to New York\'s incredible food scene',
    participants: 203,
    location: 'New York, USA',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    category: 'food',
    tags: ['pizza', 'bagels', 'fine-dining', 'street-food', 'desserts'],
    createdAt: '2024-01-05T09:15:00Z',
    lastMessage: 'Best pizza in Brooklyn is definitely at...',
    lastMessageTime: '3 days ago',
    unreadCount: 7,
    isSubscribed: false,
    moderators: ['u4'],
    messages: [],
  },
};