//Mock data for itinerary
import type { ititerary } from './planner.types';


export const mockititerarys: Record<string, ititerary> = {
  'it1': {
    ititeraryId: 'it1',
    userId: '1',
    name: 'Bali Adventure',
    city: 'Bali',
    country: 'Indonesia',
    description: 'A 3-day adventure exploring the best of Bali, Indonesia.',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4',
    trendingScore: 98,
    ecoScore: 90,
    bestTimeToVisit: 'April to October',
    averageCost: '$50-100 per day',
    totalcost: 270,
    localTips: 'Rent a scooter to get around the island, but be careful with traffic. Try the local Babi Guling (suckling pig) and visit waterfalls in the north.',
    startDate: '2025-05-15T10:00:00Z',
    endDate: '2025-05-17T10:00:00Z',
    duration: 3,
    isfavorite: false,
    isShared: false,
    isPublic: true,
    ItineraryDays: [
      {
        id: '1',
        date: '2025-05-15T10:00:00Z',
        activitys: [
          {
            id: 'a1',
            name: 'Temple Visit',
            description: 'Visit the famous sunrise temple.',
            imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
            location: { lat: 34.052, lng: -118.243 },
            rating: 4.8,
            reviewsCount: 120,
            priceLevel: 2,
            openingHours: ['06:00', '18:00'],
            tags: ['temple', 'spiritual', 'landmark'],
            type: 'landmark',
            isUpvoted: false,
            isDownvoted: false,
            upvoteCount: 10,
            downvoteCount: 2,
            AiSummary: 'Visit the famous sunrise temple in Bali, known for its stunning views and spiritual significance. A must-see for any traveler to the island.',
            AiSummaryRating: 4.8,
          },
          {
            id: 'a8',
            name: 'Eiffel Tower Visit',
            description: 'Climb the Eiffel Tower and enjoy the view.',
            imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
            location: { lat: 48.858, lng: 2.294 },
            rating: 4.7,
            reviewsCount: 400,
            cost: 30,
            openingHours: ['09:00', '23:00'],
            tags: ['tower', 'view', 'landmark'],
            type: 'landmark',
            isUpvoted: false,
            isDownvoted: false,
            upvoteCount: 20,
            downvoteCount: 5,
            AiSummary: 'Climb the Eiffel Tower for breathtaking views of Paris. The iconic landmark offers a unique perspective of the city, especially at sunset.',
            AiSummaryRating: 4.7,
          },
          {
            id: 'a9',
            name: 'Seine River Cruise',
            description: 'Evening cruise along the Seine River.',
            imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a',
            location: { lat: 48.860, lng: 2.337 },
            rating: 4.8,
            reviewsCount: 350,
            cost: 20,
            openingHours: ['18:00', '22:00'],
            tags: ['river', 'cruise', 'activity'],
            type: 'activity',
            isUpvoted: false,
            isDownvoted: false,
            upvoteCount: 15,
            downvoteCount: 3,
            AiSummary: 'Experience the beauty of Paris from the water with a Seine River cruise. Enjoy stunning views of iconic landmarks like the Eiffel Tower and Notre-Dame Cathedral.',
            AiSummaryRating: 4.8,
          },
        ],
        weather: [
          { id: 'w1', date: '2025-05-15T10:00:00Z', summary: 'Sunny', icon: 'wb-sunny', high: 29, low: 22 },
        ],
      },
      {
        id: '2',
        date: '2025-05-16T10:00:00Z',
        activitys: [
          {
            id: 'a3',
            name: 'Street Food Tour',
            description: 'Taste the best local street food.',
            imageUrl: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
            location: { lat: 34.055, lng: -118.248 },
            rating: 4.7,
            reviewsCount: 80,
            cost: 50,
            openingHours: ['10:00', '22:00'],
            tags: ['food', 'tour', 'local'],
            type: 'activity',
            isUpvoted: false,
            isDownvoted: false,
            upvoteCount: 5,
            downvoteCount: 1,
            AiSummary: 'Experience the vibrant street food scene in Bali, Indonesia. Taste local delicacies and explore the bustling markets with a guided tour.',
            AiSummaryRating: 4.7,
          },
          {
            id: 'a10',
            name: 'Louvre Museum',
            description: 'Explore the world-famous Louvre Museum.',
            imageUrl: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
            location: { lat: 48.860, lng: 2.337 },
            rating: 4.8,
            reviewsCount: 350,
            cost: 20,
            openingHours: ['09:00', '18:00'],
            tags: ['museum', 'art', 'activity'],
            type: 'activity',
            isUpvoted: false,
            isDownvoted: false,
            upvoteCount: 15,
            downvoteCount: 3,
            AiSummary: 'Explore the world-famous Louvre Museum in Paris, home to thousands of works of art, including the Mona Lisa and the Venus de Milo. A must-visit for art lovers.',
            AiSummaryRating: 4.8,
          },
        ],
        weather: [
          { id: 'w2', date: '2025-05-16T10:00:00Z', summary: 'Partly Cloudy', icon: 'cloud', high: 27, low: 21 },
        ],
      },
      {
        id: '3',
        date: '2025-05-17T10:00:00Z',
        activitys: [
          {
            id: 'a5',
            name: 'Beach Relaxation',
            description: 'Relax at the beautiful beach.',
            imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
            location: { lat: 34.025, lng: -118.503 },
            rating: 4.9,
            reviewsCount: 200,
            cost: 50,
            openingHours: ['08:00', '20:00'],
            tags: ['beach', 'relax', 'nature'],
            type: 'accommodation',
            isUpvoted: false,
            isDownvoted: false,
            upvoteCount: 15,
            downvoteCount: 3,
            AiSummary: 'Relax at the beautiful beach in Bali, Indonesia. Enjoy the sun, sand, and sea while soaking up the tropical atmosphere.',
            AiSummaryRating: 4.9,
          },
         {
            id: 'a7',
            name: 'Arashiyama Bamboo Grove',
            description: 'Walk through the serene bamboo forest.',
            imageUrl: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
            location: { lat: 35.009, lng: 135.667 },
            rating: 4.8,
            reviewsCount: 220,
            cost: 100,
            openingHours: ['08:00', '17:00'],
            tags: ['bamboo', 'nature', 'activity'],
            type: 'food',
            isUpvoted: false,
            isDownvoted: false,
            upvoteCount: 8,
            downvoteCount: 1,
            AiSummary: 'Walk through the serene bamboo forest in Arashiyama, Kyoto. The towering bamboo stalks create a tranquil atmosphere, perfect for a peaceful stroll or photography.',
            AiSummaryRating: 4.8,
          },
        ],
        weather: [
          { id: 'w3', date: '2025-05-17T10:00:00Z', summary: 'Showers', icon: 'umbrella', high: 25, low: 20 },
        ],
      },
    ],
    Highlights: [
      {
        id: 'h1',
        name: 'Sunrise Temple Visit',
        description: 'Beautiful temple known for its sunrise views',
        icon: 'fort'
      },
      {
        id: 'h2',
        name: 'Local Street Food Tour',
        description: 'Experience authentic Balinese cuisine',
        icon: 'fastfood'
      },
      {
        id: 'h3',
        name: 'Beach Relaxation',
        description: 'Relax at pristine Balinese beaches',
        icon: 'beach_access'
      },
    ],
    Comments: [
      {
        id: 'c1',
        userId: '2',
        itineraryId: 'it1',
        content: 'Amazing trip! The temple visit was unforgettable.',
        createdAt: '2025-05-16T10:00:00Z',
        updatedAt: '2025-05-16T10:00:00Z',
        likes: 5,
        dislikes: 0,
        isliked: false,
        isdislicked: false,
      },
      {
        id: 'c2',
        userId: '3',
        itineraryId: 'it1',
        content: 'The street food tour was a highlight! Highly recommend.',
        createdAt: '2025-05-16T12:00:00Z',
        updatedAt: '2025-05-16T12:00:00Z',
        likes: 3,
        dislikes: 1,
        isliked: false,
        isdislicked: false,
      },
    ]
  },
  'it2': {
    ititeraryId: 'it2',
    userId: '1',
    name: 'Kyoto Cultural Journey',
    city: 'Kyoto',
    country: 'Japan',
    description: 'A cultural 3-day journey through Kyoto, Japan.',
    imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e',
    trendingScore: 92,
    ecoScore: 65,
    bestTimeToVisit: 'March-May and October-November',
    averageCost: '$70-120 per day',
    totalcost: 175,
    localTips: 'Rent a bicycle to explore the city. Try kaiseki cuisine and matcha tea ceremonies.',
    startDate: '2025-04-05T10:00:00Z',
    endDate: '2025-04-07T10:00:00Z',
    duration: 3,
    isfavorite: false,
    isShared: true,
    isPublic: false,
    ItineraryDays: [
      {
        id: '1',
        date: '2025-04-05T10:00:00Z',
        activitys: [
          {
            id: 'a6',
            name: 'Fushimi Inari Shrine',
            description: 'Explore the famous shrine with thousands of torii gates.',
            imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
            location: { lat: 34.967, lng: 135.772 },
            rating: 4.9,
            reviewsCount: 500,
            cost: 20,
            openingHours: ['07:00', '18:00'],
            tags: ['shrine', 'culture', 'landmark'],
            type: 'landmark',
            isUpvoted: false,
            isDownvoted: false,
            upvoteCount: 20,
            downvoteCount: 5,
            AiSummary: 'Fushimi Inari Shrine is a famous Shinto shrine in Kyoto, known for its thousands of vermilion torii gates that create stunning trails up the sacred Mount Inari.',
            AiSummaryRating: 4.9,
          },
        ],
        weather: [
          { id: 'w7', date: '2025-04-05T10:00:00Z', summary: 'Cloudy', icon: 'cloud', high: 20, low: 12 },
        ],
      },
      {
        id: '2',
        date: '2025-04-06T10:00:00Z',
        activitys: [
          {
            id: 'a7',
            name: 'Arashiyama Bamboo Grove',
            description: 'Walk through the serene bamboo forest.',
            imageUrl: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
            location: { lat: 35.009, lng: 135.667 },
            rating: 4.8,
            reviewsCount: 220,
            cost: 100,
            openingHours: ['08:00', '17:00'],
            tags: ['bamboo', 'nature', 'activity'],
            type: 'activity',
            isUpvoted: false,
            isDownvoted: false,
            upvoteCount: 8,
            downvoteCount: 1,
            AiSummary: 'Walk through the serene bamboo forest in Arashiyama, Kyoto. The towering bamboo stalks create a tranquil atmosphere, perfect for a peaceful stroll or photography.',
            AiSummaryRating: 4.8,
          },
        ],
        weather: [
          { id: 'w8', date: '2025-04-06T10:00:00Z', summary: 'Rainy', icon: 'umbrella', high: 18, low: 10 },
        ],
      },
      {
        id: '3',
        date: '2025-04-07T10:00:00Z',
        activitys: [
          {
            id: 'a8',
            name: 'Traditional Tea Ceremony',
            description: 'Experience a traditional Japanese tea ceremony.',
            imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e',
            location: { lat: 35.0116, lng: 135.7681 },
            rating: 4.7,
            reviewsCount: 150,
            cost: 25,
            openingHours: ['10:00', '17:00'],
            tags: ['tea', 'culture', 'activity'],
            type: 'activity',
            isUpvoted: false,
            isDownvoted: false,
            upvoteCount: 10,
            downvoteCount: 2,
            AiSummary: 'Experience a traditional Japanese tea ceremony in Kyoto. Learn about the history and significance of this cultural practice while enjoying matcha tea and traditional sweets.',
            AiSummaryRating: 4.7,
          },
          {
            id: 'a9',
            name: 'Kinkaku-ji (Golden Pavilion)',
            description: 'Visit the stunning Zen Buddhist temple.',
            imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e',
            location: { lat: 35.0394, lng: 135.7292 },
            rating: 4.9,
            reviewsCount: 300,
            cost: 30,
            openingHours: ['09:00', '17:00'],
            tags: ['temple', 'landmark', 'culture'],
            type: 'landmark',
            isUpvoted: false,
            isDownvoted: false,
            upvoteCount: 25,
            downvoteCount: 3,
            AiSummary: 'Kinkaku-ji, also known as the Golden Pavilion, is a Zen Buddhist temple in Kyoto. It is renowned for its stunning architecture and beautiful gardens, making it a must-visit landmark.',
            AiSummaryRating: 4.9,
          }
        ],
        weather: [
          { id: 'w9', date: '2025-04-07T10:00:00Z', summary: 'Clear', icon: 'wb-sunny', high: 21, low: 13 },
        ],
      },
    ],
    Highlights: [
      {
        id: 'h6',
        name: 'Fushimi Inari Shrine',
        description: 'Iconic shrine with thousands of vermilion torii gates',
        icon: 'fort'
      },
      {
        id: 'h7',
        name: 'Arashiyama Bamboo Grove',
        description: 'Picturesque walking paths through towering bamboo',
        icon: 'nature'
      },
      {
        id: 'h8',
        name: 'Traditional Tea Ceremony',
        description: 'Experience authentic Japanese tea culture',
        icon: 'coffee'
      },
    ],
    Comments: [
      {
        id: 'c3',
        userId: 'user123',
        itineraryId: 'it2',
        content: 'The bamboo grove was breathtaking! A must-visit in Kyoto.',
        createdAt: '2025-04-08T10:00:00Z',
        updatedAt: '2025-04-08T10:00:00Z',
        likes: 8,
        dislikes: 1,
        isliked: false,
        isdislicked: false,
      },
      {
        id: 'c4',
        userId: 'user789',
        itineraryId: 'it2',
        content: 'The tea ceremony was a unique experience. Highly recommend!',
        createdAt: '2025-04-08T12:00:00Z',
        updatedAt: '2025-04-08T12:00:00Z',
        likes: 5,
        dislikes: 0,
        isliked: false,
        isdislicked: false,
      },
    ],
  },
} as unknown as Record<string, ititerary>;