// Mock data for User Profile
import type { UserProfile } from './profile.types';

export const mockUserProfile: Record<string, UserProfile> = {
  'user123': {
    id: 'user123',
    username: 'john_doe',
    email: 'demo@travelco.com',
    phone: '',
    name: 'John Doe',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    location: 'New York, USA',
    locationCoordinates: { latitude: 40.7128, longitude: -74.0060 },
    stats: { followers: 100, following: 50, posts: 25 },
    credits: 1000,
    isVerified: true,
    lastActive: new Date().toISOString(),
    memberSince: new Date('2023-01-01').toISOString(),
    isFollowing: false,
    isFollowingBack: false,
    isBlocked: false,
    isFriend: false,
    isPremium: true,
    isSubscribed: true,
    badges: ['Traveler', 'Foodie', 'Explorer'],
    bio: 'Travel enthusiast and food lover. Always looking for the next adventure!',
    interests: ['Travel', 'Food', 'Photography'],
    friends: ['1', '2', '3'],
    travelHistory: ['Paris', 'Tokyo', 'New York'],
    travelGoals: ['Bali', 'Sydney', 'Cape Town'],
    chatRooms: ['room1', 'room2'],
    itineraries: ['it1', 'it2'],
    favoriteitineraries: ['it1'],
    travelPreferences: {
      preferredDestinations: ['Bali', 'Sydney', 'Cape Town'],
      travelStyles: ['Adventure', 'Relaxation'],
      preferredActivities: ['Hiking', 'Beach'],
      budgetRange: { min: 1000, max: 5000 },
      travelCompanions: ['Friends', 'Family'],
      accommodationPreferences: ['Hotel', 'Hostel'],
      transportationPreferences: ['Car', 'Public Transport'],
      dietaryRestrictions: ['Vegetarian'],
      accessibilityNeeds: [],
      languagePreferences: ['English', 'Spanish'],
      ecoFriendlyPreferences: true,
    },
    notifications: {
      newMessages: true,
      itineraryUpdates: true,
      friendRequests: true,
      travelDeals: true,
      ecoImpactUpdates: true,
    },
    privacySettings: {
      profileVisibility: 'public',
      locationSharing: true,
      dataSharingWithPartners: false,
    },
  },

  'user456': {
    id: 'user456',
    username: 'jane_doe',
    email: 'demo2@travelco.com',
    phone: '',
    name: 'Jane Doe',
    avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
    location: 'Los Angeles, USA',
    locationCoordinates: { latitude: 34.0522, longitude: -118.2437 },
    stats: { followers: 200, following: 100, posts: 50 },
    credits: 2000,
    isVerified: false,
    lastActive: new Date().toISOString(),
    memberSince: new Date('2023-02-01').toISOString(),
    isFollowing: true,
    isFollowingBack: true,
    isBlocked: false,
    isFriend: true,
    isPremium: false,
    isSubscribed: false,
    badges: ['Traveler', 'Foodie'],
    bio: 'Food lover and travel enthusiast. Always looking for the next adventure!',
    interests: ['Travel', 'Food'],
    friends: ['1', '3'],
    travelHistory: ['Paris', 'Tokyo', 'New York'],
    travelGoals: ['Bali', 'Sydney', 'Cape Town'],
    chatRooms: ['room1', 'room2'],
    itineraries: ['it1', 'it2'],
    favoriteitineraries: ['it1'],
    travelPreferences: {
      preferredDestinations: ['Bali', 'Sydney', 'Cape Town'],
      travelStyles: ['Adventure', 'Relaxation'],
      preferredActivities: ['Hiking', 'Beach'],
      budgetRange: { min: 1000, max: 5000 },
      travelCompanions: ['Friends', 'Family'],
      accommodationPreferences: ['Hotel', 'Hostel'],
      transportationPreferences: ['Car', 'Public Transport'],
      dietaryRestrictions: ['Vegetarian'],
      accessibilityNeeds: [],
      languagePreferences: ['English', 'Spanish'],
      ecoFriendlyPreferences: true,
    },
    notifications: {
      newMessages: true,
      itineraryUpdates: true,
      friendRequests: true,
      travelDeals: true,
      ecoImpactUpdates: true,
    },
    privacySettings: {
      profileVisibility: 'public',
      locationSharing: true,
      dataSharingWithPartners: false,
    },
  },

  'user789': {
    id: 'user789',
    username: 'mark_smith',
    email: 'demo3@travelco.com',
    phone: '',
    name: 'Mark Smith',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    location: 'Chicago, USA',
    locationCoordinates: { latitude: 41.8781, longitude: -87.6298 },
    stats: { followers: 150, following: 75, posts: 30 },
    credits: 1500,
    isVerified: true,
    lastActive: new Date().toISOString(),
    memberSince: new Date('2023-03-01').toISOString(),
    isFollowing: false,
    isFollowingBack: false,
    isBlocked: false,
    isFriend: false,
    isPremium: true,
    isSubscribed: true,
    badges: ['Traveler', 'Explorer'],
    bio: 'Explorer and adventure seeker. Always looking for the next challenge!',
    interests: ['Travel', 'Adventure'],
    friends: ['john_doe', 'jane_doe'],
    travelHistory: ['Paris', 'Tokyo', 'New York'],
    travelGoals: ['Bali', 'Sydney', 'Cape Town'],
    chatRooms: ['room1', 'room2'],
    itineraries: ['it1', 'it2'],
    favoriteitineraries: ['it1'],
    travelPreferences: {
      preferredDestinations: ['Bali', 'Sydney', 'Cape Town'],
      travelStyles: ['Adventure', 'Relaxation'],
      preferredActivities: ['Hiking', 'Beach'],
      budgetRange: { min: 1000, max: 5000 },
      travelCompanions: ['Friends', 'Family'],
      accommodationPreferences: ['Hotel', 'Hostel'],
      transportationPreferences: ['Car', 'Public Transport'],
      dietaryRestrictions: ['Vegetarian'],
      accessibilityNeeds: [],
      languagePreferences: ['English', 'Spanish'],
      ecoFriendlyPreferences: true,
    },
    notifications: {
      newMessages: true,
      itineraryUpdates: true,
      friendRequests: true,
      travelDeals: true,
      ecoImpactUpdates: true,
    },
    privacySettings: {
      profileVisibility: 'public',
      locationSharing: true,
      dataSharingWithPartners: false,
    },
  },
};
