//Mock data for User Profile
import type { UserProfile } from './profile.types';

export const mockUserProfile: Record<string,UserProfile> = {
  '1': {
  id: '1',
  username: 'john_doe',
  email: 'demo@travelco.com',
  phone: '',
  name: 'John Doe',
  avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
  location: 'New York, USA',
    locationCoordinates: { latitude: 40.7128, longitude: -74.0060 },
  stats: { followers: 100, following: 50, posts: 25 },
  credits: 1000,
  isVerified: true,
  lastActive: new Date().toISOString(),
  memberSince: new Date('2023-01-01').toISOString(),
  isFollowing: false,
  isFollowingBack: false,
  isBlocked: false,
  isFriend: false,
  isPremium: true,
  isSubscribed: true,
  badges: ['Traveler', 'Foodie', 'Explorer'],
  bio: 'Travel enthusiast and food lover. Always looking for the next adventure!',
  interests: ['Travel', 'Food', 'Photography'],
  friends: ['1', '2', '3'],
  travelHistory: ['Paris', 'Tokyo', 'New York'],
  travelGoals: ['Bali', 'Sydney', 'Cape Town'],
  EcoImpact: {
    ecoScore: 85,
    itineraryId: '1',
    stats: [
      {
        label: 'Carbon Footprint',
        value: '2.5 tons',
        icon: 'energy-savings-leaf',
      },
      {
        label: 'Water Usage',
        value: '1500 liters',
        icon: 'water-drop',
      },
      {
        label: 'Waste Generated',
        value: '50 kg',
        icon: 'restore-from-trash',
      },
    ],
  },
  budget: {
    total: 5000,
    spent: 2000,
    currency: 'USD',
    alerts: [
      {
        id: '1',
        message: 'You have spent 40% of your budget.',
        type: 'warning',
      },
      {
        id: '2',
        message: 'You are on track to stay within budget.',
        type: 'positive',
      },
      {
        id: '3',
        message: 'You have 60% of your budget left.',
        type: 'positive',
      },
    ],
  },
  chatRooms: ['room1', 'room2'],
  itineraries: ['it1', 'it2'],
  travelPreferences: {
    preferredDestinations: ['Bali', 'Sydney', 'Cape Town'],
    travelStyles: ['Adventure', 'Relaxation'],
    preferredActivities: ['Hiking', 'Beach'],
    budgetRange: {
      min: 1000,
      max: 5000,
    },
    travelCompanions: ['Friends', 'Family'],
    accommodationPreferences: ['Hotel', 'Hostel'],
    transportationPreferences: ['Car', 'Public Transport'],
    dietaryRestrictions: ['Vegetarian'],
    accessibilityNeeds: [],
    languagePreferences: ['English', 'Spanish'],
    ecoFriendlyPreferences: true,
  },
notifications: {
    newMessages: true,
    itineraryUpdates: true,
    friendRequests: true,
    travelDeals: true,
    ecoImpactUpdates: true,
  },
  privacySettings: {
    profileVisibility: 'public',
    locationSharing: true,
    dataSharingWithPartners: false,
  },
},
  '2': {
  id: '2',
  username: 'jane_doe',
  email: 'demo2@travelco.com',
  phone: '',
  name: 'Jane Doe',
  avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
  location: 'Los Angeles, USA',
  locationCoordinates: { latitude: 34.0522, longitude: -118.2437 },
  stats: { followers: 200, following: 100, posts: 50 },
  credits: 2000,
  isVerified: false,
  lastActive: new Date().toISOString(),
  memberSince: new Date('2023-02-01').toISOString(),
  isFollowing: true,
  isFollowingBack: true,
  isBlocked: false,
  isFriend: true,
  isPremium: false,
  isSubscribed: false,
  badges: ['Traveler', 'Foodie'],
  bio: 'Food lover and travel enthusiast. Always looking for the next adventure!',
  interests: ['Travel', 'Food'],
  friends: ['1', '3'],
  travelHistory: ['Paris', 'Tokyo', 'New York'],
  travelGoals: ['Bali', 'Sydney', 'Cape Town'],
  EcoImpact: {
    ecoScore: 75,
    itineraryId: '2',
    stats: [
      {
        label: 'Carbon Footprint',
        value: '3.0 tons',
        icon: 'energy-savings-leaf',
      },
      {
        label: 'Water Usage',
        value: '2000 liters',
        icon: 'water-drop',
      },
      {
        label: 'Waste Generated',
        value: '60 kg',
        icon: 'restore-from-trash',
      },
    ],
  },
  budget: {
    total: 3000,
    spent: 1000,
    currency: 'USD',
    alerts: [
      {
        id: '1',
        message: 'You have spent 33% of your budget.',
        type: 'warning',
      },
      {
        id: '2',
        message: 'You are on track to stay within budget.',
        type: 'positive',
      },
      {
        id: '3',
        message: 'You have 67% of your budget left.',
        type: 'positive',
      },
    ],
  },
  chatRooms: ['room1', 'room2'],
  itineraries: ['it1', 'it2'],
  travelPreferences: {
    preferredDestinations: ['Bali', 'Sydney', 'Cape Town'],
    travelStyles: ['Adventure', 'Relaxation'],
    preferredActivities: ['Hiking', 'Beach'],
    budgetRange: {
      min: 1000,
      max: 5000,
    },
    travelCompanions: ['Friends', 'Family'],
    accommodationPreferences: ['Hotel', 'Hostel'],
    transportationPreferences: ['Car', 'Public Transport'],
    dietaryRestrictions: ['Vegetarian'],
    accessibilityNeeds: [],
    languagePreferences: ['English', 'Spanish'],
    ecoFriendlyPreferences: true,
  },
  notifications: {
    newMessages: true,
    itineraryUpdates: true,
    friendRequests: true,
    travelDeals: true,
    ecoImpactUpdates: true,
  },
  privacySettings: {
    profileVisibility: 'public',
    locationSharing: true,
    dataSharingWithPartners: false,
  }
},
  '3': {
  id: '3',
  username: 'mark_smith',
  email: 'demo3@travelco.com',
  phone: '',
  name: 'Mark Smith',
  avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
  location: 'Chicago, USA',
  locationCoordinates: { latitude: 41.8781, longitude: -87.6298 },
  stats: { followers: 150, following: 75, posts: 30 },
  credits: 1500,
  isVerified: true,
  lastActive: new Date().toISOString(),
  memberSince: new Date('2023-03-01').toISOString(),
  isFollowing: false,
  isFollowingBack: false,
  isBlocked: false,
  isFriend: false,
  isPremium: true,
  isSubscribed: true,
  badges: ['Traveler', 'Explorer'],
  bio: 'Explorer and adventure seeker. Always looking for the next challenge!',
  interests: ['Travel', 'Adventure'],
  friends: ['john_doe', 'jane_doe'],
  travelHistory: ['Paris', 'Tokyo', 'New York'],
  travelGoals: ['Bali', 'Sydney', 'Cape Town'],
  EcoImpact: {
    ecoScore: 90,
    itineraryId: '3',
    stats: [
      {
        label: 'Carbon Footprint',
        value: '2.0 tons',
        icon: 'energy-savings-leaf',
      },
      {
        label: 'Water Usage',
        value: '1200 liters',
        icon: 'water-drop',
      },
      {
        label: 'Waste Generated',
        value: '40 kg',
        icon: 'restore-from-trash',
      },
    ],
  },
  budget: {
    total: 4000,
    spent: 1500,
    currency: 'USD',
    alerts: [
      {
        id: '1',
        message: 'You have spent 37.5% of your budget.',
        type: 'warning',
      },
      {
        id: '2',
        message: 'You are on track to stay within budget.',
        type: 'positive',
      },
      {
        id: '3',
        message: 'You have 62.5% of your budget left.',
        type: 'positive',
      },
    ],
  },
  chatRooms: ['room1', 'room2'],
  itineraries: ['it1', 'it2'],
  travelPreferences: {
    preferredDestinations: ['Bali', 'Sydney', 'Cape Town'],
    travelStyles: ['Adventure', 'Relaxation'],
    preferredActivities: ['Hiking', 'Beach'],
    budgetRange: {
      min: 1000,
      max: 5000,
    },
    travelCompanions: ['Friends', 'Family'],
    accommodationPreferences: ['Hotel', 'Hostel'],
    transportationPreferences: ['Car', 'Public Transport'],
    dietaryRestrictions: ['Vegetarian'],
    accessibilityNeeds: [],
    languagePreferences: ['English', 'Spanish'],
    ecoFriendlyPreferences: true,
  },
  notifications: {
    newMessages: true,
    itineraryUpdates: true,
    friendRequests: true,
    travelDeals: true,
    ecoImpactUpdates: true,
  },
  privacySettings: {
    profileVisibility: 'public',
    locationSharing: true,
    dataSharingWithPartners: false,
  },
}
};